apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret.yaml

images:
  - name: nimbus/shortener-api
    newTag: local
  - name: nimbus/redirect-svc
    newTag: local
  - name: nimbus/analytics-worker
    newTag: local
  - name: nimbus/dashboard-ui
    newTag: local
