apiVersion: v1
kind: Secret
metadata:
  name: nimbus-secrets
type: Opaque
stringData:
  database-url: "postgresql://nimbus:nimbus-local-dev@postgres:5432/nimbus"
  redis-url: "redis://redis:6379"
  sqs-queue-url: "http://sqs.ap-south-1.localhost.localstack.cloud:4566/000000000000/click-events"
  sqs-endpoint: "http://localstack:4566"
  otlp-endpoint: "http://otel-collector.monitoring.svc.cluster.local:4317"
