apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: database-url
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: sqs-queue-url
            - name: SQS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: sqs-endpoint
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
