apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nimbus
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: shortener-api
  endpoints:
    - port: "80"
      path: /metrics
      interval: 15s
