apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nimbus-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: localstack
    kind: SecretStore
  target:
    name: nimbus-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: nimbus/local/app-secrets
        property: database_url
    - secretKey: redis-url
      remoteRef:
        key: nimbus/local/app-secrets
        property: redis_url
    - secretKey: sqs-queue-url
      remoteRef:
        key: nimbus/local/app-secrets
        property: sqs_queue_url
    - secretKey: sqs-endpoint
      remoteRef:
        key: nimbus/local/app-secrets
        property: sqs_endpoint
    - secretKey: otlp-endpoint
      remoteRef:
        key: nimbus/local/app-secrets
        property: otlp_endpoint
