apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3
          env:
            - name: SERVICES
              value: sqs
            - name: AWS_DEFAULT_REGION
              value: ap-south-1
          ports:
            - containerPort: 4566
          volumeMounts:
            - name: init-script
              mountPath: /etc/localstack/init/ready.d
      volumes:
        - name: init-script
          configMap:
            name: localstack-init
            defaultMode: 0755
